import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://geistsans.com/font.css" />
      </head>
      <body style={{ fontFamily: 'Geist, sans-serif' }}>
        {children}
      </body>
    </html>
  );
}
